//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFApplication.Resources.ControlResources", typeof(ControlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message….
        /// </summary>
        public static string ChatMsg {
            get {
                return ResourceManager.GetString("ChatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes for: {0}.
        /// </summary>
        public static string DPCVoteFor {
            get {
                return ResourceManager.GetString("DPCVoteFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string EGVNickname {
            get {
                return ResourceManager.GetString("EGVNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string EGVRole {
            get {
                return ResourceManager.GetString("EGVRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string EGVStatus {
            get {
                return ResourceManager.GetString("EGVStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string EGVUsername {
            get {
                return ResourceManager.GetString("EGVUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to an existing lobby.
        /// </summary>
        public static string HVConnectLobby {
            get {
                return ResourceManager.GetString("HVConnectLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create lobby.
        /// </summary>
        public static string HVCreateLobby {
            get {
                return ResourceManager.GetString("HVCreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your nickname.
        /// </summary>
        public static string HVNickname {
            get {
                return ResourceManager.GetString("HVNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your nickname.
        /// </summary>
        public static string IGSVEnterNickname {
            get {
                return ResourceManager.GetString("IGSVEnterNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string IVTeams {
            get {
                return ResourceManager.GetString("IVTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string JoinButton {
            get {
                return ResourceManager.GetString("JoinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last message….
        /// </summary>
        public static string LGSVLastMessage {
            get {
                return ResourceManager.GetString("LGSVLastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server created at port {0}.
        /// </summary>
        public static string LHVMServerCreated {
            get {
                return ResourceManager.GetString("LHVMServerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect by IP.
        /// </summary>
        public static string LLVConnect {
            get {
                return ResourceManager.GetString("LLVConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4 adress.
        /// </summary>
        public static string LLVIPAdress {
            get {
                return ResourceManager.GetString("LLVIPAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the city….
        /// </summary>
        public static string LVCityName {
            get {
                return ResourceManager.GetString("LVCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day type.
        /// </summary>
        public static string LVDayType {
            get {
                return ResourceManager.GetString("LVDayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string LVDone {
            get {
                return ResourceManager.GetString("LVDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max players.
        /// </summary>
        public static string LVMaxPlayers {
            get {
                return ResourceManager.GetString("LVMaxPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string LVMChatSystem {
            get {
                return ResourceManager.GetString("LVMChatSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :{0}: Has arrived!.
        /// </summary>
        public static string LVMNewPlayer {
            get {
                return ResourceManager.GetString("LVMNewPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :{0}: Has been disconnected..
        /// </summary>
        public static string LVMPlayerLeft {
            get {
                return ResourceManager.GetString("LVMPlayerLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;Has arrived!&lt;.
        /// </summary>
        public static string LVNewClient {
            get {
                return ResourceManager.GetString("LVNewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night type.
        /// </summary>
        public static string LVNightType {
            get {
                return ResourceManager.GetString("LVNightType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string LVReady {
            get {
                return ResourceManager.GetString("LVReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial settings.
        /// </summary>
        public static string LVTrialSettings {
            get {
                return ResourceManager.GetString("LVTrialSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MWInfo {
            get {
                return ResourceManager.GetString("MWInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        public static string MWMainMenu {
            get {
                return ResourceManager.GetString("MWMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MWSettings {
            get {
                return ResourceManager.GetString("MWSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decedent&apos;s chat.
        /// </summary>
        public static string RGVDecedentChat {
            get {
                return ResourceManager.GetString("RGVDecedentChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General chat.
        /// </summary>
        public static string RGVGeneralChat {
            get {
                return ResourceManager.GetString("RGVGeneralChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string TPCNoneTarget {
            get {
                return ResourceManager.GetString("TPCNoneTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target {0}.
        /// </summary>
        public static string TPCTarget {
            get {
                return ResourceManager.GetString("TPCTarget", resourceCulture);
            }
        }
    }
}
