//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFApplication.Resources.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballot.
        /// </summary>
        internal static string BallotDayOption {
            get {
                return ResourceManager.GetString("BallotDayOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballot + Trial.
        /// </summary>
        internal static string BallotTrialDayOption {
            get {
                return ResourceManager.GetString("BallotTrialDayOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen.
        /// </summary>
        internal static string CitizenRole {
            get {
                return ResourceManager.GetString("CitizenRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Night.
        /// </summary>
        internal static string ClassicNightOption {
            get {
                return ResourceManager.GetString("ClassicNightOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counselor.
        /// </summary>
        internal static string CounselorRole {
            get {
                return ResourceManager.GetString("CounselorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultist.
        /// </summary>
        internal static string CultistRole {
            get {
                return ResourceManager.GetString("CultistRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultus Leader.
        /// </summary>
        internal static string CultusLeaderRole {
            get {
                return ResourceManager.GetString("CultusLeaderRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursed.
        /// </summary>
        internal static string CursedRole {
            get {
                return ResourceManager.GetString("CursedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Descriptions.
        /// </summary>
        internal static string DescriptionNightOption {
            get {
                return ResourceManager.GetString("DescriptionNightOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Sequence.
        /// </summary>
        internal static string DetailedNightOption {
            get {
                return ResourceManager.GetString("DetailedNightOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detective.
        /// </summary>
        internal static string DetectiveRole {
            get {
                return ResourceManager.GetString("DetectiveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string DoctorRole {
            get {
                return ResourceManager.GetString("DoctorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        internal static string DriverRole {
            get {
                return ResourceManager.GetString("DriverRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godfather.
        /// </summary>
        internal static string GodfatherRole {
            get {
                return ResourceManager.GetString("GodfatherRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mafia.
        /// </summary>
        internal static string MafiaRole {
            get {
                return ResourceManager.GetString("MafiaRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majority.
        /// </summary>
        internal static string MajorityDayOption {
            get {
                return ResourceManager.GetString("MajorityDayOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majority + Trial.
        /// </summary>
        internal static string MajorityTrialDayOption {
            get {
                return ResourceManager.GetString("MajorityTrialDayOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mason.
        /// </summary>
        internal static string MasonRole {
            get {
                return ResourceManager.GetString("MasonRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policeman.
        /// </summary>
        internal static string PolicemanRole {
            get {
                return ResourceManager.GetString("PolicemanRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prostitute.
        /// </summary>
        internal static string ProstituteRole {
            get {
                return ResourceManager.GetString("ProstituteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychic.
        /// </summary>
        internal static string PsychicRole {
            get {
                return ResourceManager.GetString("PsychicRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruit.
        /// </summary>
        internal static string RecruitRole {
            get {
                return ResourceManager.GetString("RecruitRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Killer.
        /// </summary>
        internal static string SerialKillerRole {
            get {
                return ResourceManager.GetString("SerialKillerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgeon.
        /// </summary>
        internal static string SurgeonRole {
            get {
                return ResourceManager.GetString("SurgeonRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrorist.
        /// </summary>
        internal static string TerroristRole {
            get {
                return ResourceManager.GetString("TerroristRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigilant.
        /// </summary>
        internal static string VigilanteRole {
            get {
                return ResourceManager.GetString("VigilanteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whore.
        /// </summary>
        internal static string WhoreRole {
            get {
                return ResourceManager.GetString("WhoreRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witch.
        /// </summary>
        internal static string WitchRole {
            get {
                return ResourceManager.GetString("WitchRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zombie.
        /// </summary>
        internal static string ZombieRole {
            get {
                return ResourceManager.GetString("ZombieRole", resourceCulture);
            }
        }
    }
}
