//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RoleDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoleDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFApplication.Resources.RoleDescriptions", typeof(RoleDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no special traits at night..
        /// </summary>
        public static string CitizenAbility {
            get {
                return ResourceManager.GetString("CitizenAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a regular person who believes in truth and justice..
        /// </summary>
        public static string CitizenRole {
            get {
                return ResourceManager.GetString("CitizenRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can investigate one player each night..
        /// </summary>
        public static string CounselorAbility {
            get {
                return ResourceManager.GetString("CounselorAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a counselor to the boss of a crime family..
        /// </summary>
        public static string CounselorRole {
            get {
                return ResourceManager.GetString("CounselorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You speak together at night with other Cultists. However, you can only surmise who is your leader..
        /// </summary>
        public static string CultistAbility {
            get {
                return ResourceManager.GetString("CultistAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a believer of a shadowy cult, secretly attempting to convert the town to darkness..
        /// </summary>
        public static string CultistRole {
            get {
                return ResourceManager.GetString("CultistRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may attempt to convert one person to a Cultist each night and hear everything what your minions talk about. You stay unknown for them..
        /// </summary>
        public static string CultusLeaderAbility {
            get {
                return ResourceManager.GetString("CultusLeaderAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the leader of a shadowy cult, secretly attempting to convert the town to darkness..
        /// </summary>
        public static string CultusLeaderRole {
            get {
                return ResourceManager.GetString("CultusLeaderRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultus.
        /// </summary>
        public static string CultusT {
            get {
                return ResourceManager.GetString("CultusT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You belong to CULTUS and want all roles to be dead or converted to Cultists..
        /// </summary>
        public static string CultusTeam {
            get {
                return ResourceManager.GetString("CultusTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no special traits at night. If you got killed at this time you will become a Zombie but you are not sure whether you want to..
        /// </summary>
        public static string CursedAbility {
            get {
                return ResourceManager.GetString("CursedAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a regular person who believes in justice and even do not suspect your soul is cursed..
        /// </summary>
        public static string CursedRole {
            get {
                return ResourceManager.GetString("CursedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can investigate one person&apos;s role each night..
        /// </summary>
        public static string DetectiveAbility {
            get {
                return ResourceManager.GetString("DetectiveAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a skilled tracker, learning important information on behalf of the town..
        /// </summary>
        public static string DetectiveRole {
            get {
                return ResourceManager.GetString("DetectiveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can visit someone at night to save them if someone tries to kill them..
        /// </summary>
        public static string DoctorAbility {
            get {
                return ResourceManager.GetString("DoctorAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a secret surgeon skilled in trauma care..
        /// </summary>
        public static string DoctorRole {
            get {
                return ResourceManager.GetString("DoctorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can swap two players at night, making actions that target the first player instead target the second player and vice versa..
        /// </summary>
        public static string DriverAbility {
            get {
                return ResourceManager.GetString("DriverAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a disgruntled licensed transport driver..
        /// </summary>
        public static string DriverRole {
            get {
                return ResourceManager.GetString("DriverRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may attempt to recruit one person to your clan each night..
        /// </summary>
        public static string GodfatherAbility {
            get {
                return ResourceManager.GetString("GodfatherAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a the capofamiglia of the town&apos;s organized mafia syndicate.
        /// </summary>
        public static string GodfatherRole {
            get {
                return ResourceManager.GetString("GodfatherRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can kill one player each night. If there are several mafiosos then only the mafioso will go after his target..
        /// </summary>
        public static string MafiaAbility {
            get {
                return ResourceManager.GetString("MafiaAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a lowly soldato for one of the Don&apos;s borgata..
        /// </summary>
        public static string MafiaRole {
            get {
                return ResourceManager.GetString("MafiaRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mafia.
        /// </summary>
        public static string MafiaT {
            get {
                return ResourceManager.GetString("MafiaT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You belong to MAFIA and want to kill off the Town and everyone else who would oppose you..
        /// </summary>
        public static string MafiaTeam {
            get {
                return ResourceManager.GetString("MafiaTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may collaborate with other Masons at night through the secret Mason night chat..
        /// </summary>
        public static string MasonAbility {
            get {
                return ResourceManager.GetString("MasonAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a member of a secret society..
        /// </summary>
        public static string MasonRole {
            get {
                return ResourceManager.GetString("MasonRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string NeutralT {
            get {
                return ResourceManager.GetString("NeutralT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can check one player each night for criminal activity..
        /// </summary>
        public static string PolicemanAbility {
            get {
                return ResourceManager.GetString("PolicemanAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a member of law enforcement, forced into hiding because of the threat of murder..
        /// </summary>
        public static string PolicemanRole {
            get {
                return ResourceManager.GetString("PolicemanRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can block someone&apos;s role at night, canceling their night abilities. If you got recruited by Godfather you become a Whore..
        /// </summary>
        public static string ProstituteAbility {
            get {
                return ResourceManager.GetString("ProstituteAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a scantily-clad escort, working in secret..
        /// </summary>
        public static string ProstituteRole {
            get {
                return ResourceManager.GetString("ProstituteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may collaborate with other Undeads at night and also speak with decedents..
        /// </summary>
        public static string PsychicAbility {
            get {
                return ResourceManager.GetString("PsychicAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a spiritual master whose soul is connected with decedents..
        /// </summary>
        public static string PsychicRole {
            get {
                return ResourceManager.GetString("PsychicRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no special traits at night. If you got recruited at this time you will become a Mafia..
        /// </summary>
        public static string RecruitAbility {
            get {
                return ResourceManager.GetString("RecruitAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a regular person who believes in truth and justice, and hope you will find a good job ever..
        /// </summary>
        public static string RecruitRole {
            get {
                return ResourceManager.GetString("RecruitRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can kill one target at night who you want to..
        /// </summary>
        public static string SerialKillerAbility {
            get {
                return ResourceManager.GetString("SerialKillerAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a deranged criminal who hates the world..
        /// </summary>
        public static string SerialKillerRole {
            get {
                return ResourceManager.GetString("SerialKillerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not belong to anyone and want to be the last person left alive..
        /// </summary>
        public static string SerialKillerTeam {
            get {
                return ResourceManager.GetString("SerialKillerTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can visit someone at night to save them if someone tries to kill them..
        /// </summary>
        public static string SurgeonAbility {
            get {
                return ResourceManager.GetString("SurgeonAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a secret surgeon skilled in trauma care behalf of the Mafia..
        /// </summary>
        public static string SurgeonRole {
            get {
                return ResourceManager.GetString("SurgeonRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may perform a killing spree, planting a bomb at someone&apos;s house one night, killing anyone who visits that player at the same time. You cannot be healed if you do this..
        /// </summary>
        public static string TerroristAbility {
            get {
                return ResourceManager.GetString("TerroristAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a crazed spree killer who thinks the world should be destroyed..
        /// </summary>
        public static string TerroristRole {
            get {
                return ResourceManager.GetString("TerroristRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not belong to anyone and want to kill everybody including yourself over this world..
        /// </summary>
        public static string TerroristTeam {
            get {
                return ResourceManager.GetString("TerroristTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string TownT {
            get {
                return ResourceManager.GetString("TownT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You belong to TOWN and want to lynch every criminal and evildoer..
        /// </summary>
        public static string TownTeam {
            get {
                return ResourceManager.GetString("TownTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undead.
        /// </summary>
        public static string UndeadT {
            get {
                return ResourceManager.GetString("UndeadT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You belong to UNDEAD and want all players to be dead or converted to Zombie..
        /// </summary>
        public static string UndeadTeam {
            get {
                return ResourceManager.GetString("UndeadTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may kill one target at night according how many bullets left in you cartridge..
        /// </summary>
        public static string VigilanteAbility {
            get {
                return ResourceManager.GetString("VigilanteAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a dirty cop who will ignore the law and order to enact justice..
        /// </summary>
        public static string VigilanteRole {
            get {
                return ResourceManager.GetString("VigilanteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can perform roleblock one player each night..
        /// </summary>
        public static string WhoreAbility {
            get {
                return ResourceManager.GetString("WhoreAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a dancer working for organized crime..
        /// </summary>
        public static string WhoreRole {
            get {
                return ResourceManager.GetString("WhoreRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may force one person to use their night ability on a target of your choice..
        /// </summary>
        public static string WitchAbility {
            get {
                return ResourceManager.GetString("WitchAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a malicious mystic who uses their manipulative powers for evil..
        /// </summary>
        public static string WitchRole {
            get {
                return ResourceManager.GetString("WitchRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not belong to anyone and want to survive and see the town lose..
        /// </summary>
        public static string WitchTeam {
            get {
                return ResourceManager.GetString("WitchTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can try to ressurect one person who was killed at this night and turn him into a Zombie..
        /// </summary>
        public static string ZombieAbility {
            get {
                return ResourceManager.GetString("ZombieAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a mystically survived person who still have consciousness..
        /// </summary>
        public static string ZombieRole {
            get {
                return ResourceManager.GetString("ZombieRole", resourceCulture);
            }
        }
    }
}
