//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApplication.Resources.GameStoryText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DayResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DayResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFApplication.Resources.GameStoryText.DayResources", typeof(DayResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! Voting for: .
        /// </summary>
        internal static string AttentionVoting {
            get {
                return ResourceManager.GetString("AttentionVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballot ended!.
        /// </summary>
        internal static string BallotEnded {
            get {
                return ResourceManager.GetString("BallotEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballot started!.
        /// </summary>
        internal static string BallotStarted {
            get {
                return ResourceManager.GetString("BallotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day: {0}.
        /// </summary>
        internal static string DayNumber {
            get {
                return ResourceManager.GetString("DayNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the first day decided to not lynch anyone..
        /// </summary>
        internal static string FirstDayNoLynch {
            get {
                return ResourceManager.GetString("FirstDayNoLynch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voters decided to lynch .
        /// </summary>
        internal static string LynchDecided {
            get {
                return ResourceManager.GetString("LynchDecided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today there was decided to lynch no one..
        /// </summary>
        internal static string LynchNotDecided {
            get {
                return ResourceManager.GetString("LynchNotDecided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting has started..
        /// </summary>
        internal static string MeetingStarted {
            get {
                return ResourceManager.GetString("MeetingStarted", resourceCulture);
            }
        }
    }
}
