//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApplication.Resources.GameStoryText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EndResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EndResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFApplication.Resources.GameStoryText.EndResources", typeof(EndResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chronology of actions:.
        /// </summary>
        internal static string ActionLogs {
            get {
                return ResourceManager.GetString("ActionLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The whole town was converted. The dissenters either escaped or were caught and killed. The rest are ready to commit the ritual..
        /// </summary>
        internal static string CultusWin {
            get {
                return ResourceManager.GetString("CultusWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Day -.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was elected {0} with {1} votes..
        /// </summary>
        internal static string DayUserElected {
            get {
                return ResourceManager.GetString("DayUserElected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game has been ended..
        /// </summary>
        internal static string EndGame {
            get {
                return ResourceManager.GetString("EndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last message was: {0}.
        /// </summary>
        internal static string LynchLastMessage {
            get {
                return ResourceManager.GetString("LynchLastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The town is taken under the contol of the mafia. Goverment has been deposed..
        /// </summary>
        internal static string MafiaWin {
            get {
                return ResourceManager.GetString("MafiaWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaths at morning {0}.
        /// </summary>
        internal static string MorningDeath {
            get {
                return ResourceManager.GetString("MorningDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  with Failure.
        /// </summary>
        internal static string NAFailure {
            get {
                return ResourceManager.GetString("NAFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  with Success.
        /// </summary>
        internal static string NASuccess {
            get {
                return ResourceManager.GetString("NASuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Night -.
        /// </summary>
        internal static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} .
        /// </summary>
        internal static string NightAction1 {
            get {
                return ResourceManager.GetString("NightAction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  picked {0}.
        /// </summary>
        internal static string NightAction2 {
            get {
                return ResourceManager.GetString("NightAction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0}.
        /// </summary>
        internal static string NightAction3 {
            get {
                return ResourceManager.GetString("NightAction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one wins! The town is thrown into flames, everone has dead..
        /// </summary>
        internal static string NoneWin {
            get {
                return ResourceManager.GetString("NoneWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone was killed. Serial killer has quenched his thirst for blood..
        /// </summary>
        internal static string SerialKillerWin {
            get {
                return ResourceManager.GetString("SerialKillerWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The town has been thrown into flames. All buildings are in tatters..
        /// </summary>
        internal static string TerroristWin {
            get {
                return ResourceManager.GetString("TerroristWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The justice has been restored in the town..
        /// </summary>
        internal static string TownWin {
            get {
                return ResourceManager.GetString("TownWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Turn number {0} --.
        /// </summary>
        internal static string TurnNumber {
            get {
                return ResourceManager.GetString("TurnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The town was abandoned to the dead..
        /// </summary>
        internal static string UndeadWin {
            get {
                return ResourceManager.GetString("UndeadWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner is .
        /// </summary>
        internal static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The witch and her magic have won..
        /// </summary>
        internal static string WitchWin {
            get {
                return ResourceManager.GetString("WitchWin", resourceCulture);
            }
        }
    }
}
