//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApplication.Resources.GameStoryText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MorningResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MorningResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFApplication.Resources.GameStoryText.MorningResources", typeof(MorningResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of us did not survive the night..
        /// </summary>
        internal static string DayBreak1 {
            get {
                return ResourceManager.GetString("DayBreak1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A veritable Armageddon decimated the town last night..
        /// </summary>
        internal static string DayBreak10_11 {
            get {
                return ResourceManager.GetString("DayBreak10_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literally the entire town was obliterated last night..
        /// </summary>
        internal static string DayBreak12_13 {
            get {
                return ResourceManager.GetString("DayBreak12-13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setup is shit..
        /// </summary>
        internal static string DayBreak14_MORE {
            get {
                return ResourceManager.GetString("DayBreak14_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of us did not survive the night..
        /// </summary>
        internal static string DayBreak2_3 {
            get {
                return ResourceManager.GetString("DayBreak2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many of us perished last night..
        /// </summary>
        internal static string DayBreak4_5 {
            get {
                return ResourceManager.GetString("DayBreak4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mass quantity of people died last night..
        /// </summary>
        internal static string DayBreak6_7 {
            get {
                return ResourceManager.GetString("DayBreak6_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most of the entire town was wiped out last night..
        /// </summary>
        internal static string DayBreak8_9 {
            get {
                return ResourceManager.GetString("DayBreak8_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He/She was run over by a car..
        /// </summary>
        internal static string DriverD {
            get {
                return ResourceManager.GetString("DriverD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to His/Her last will was: .
        /// </summary>
        internal static string LastWill {
            get {
                return ResourceManager.GetString("LastWill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He/She was shot at close range.
        ///He/She was also riddled with bullets at close range.
        ///There were signs of struggle. He/she was shot at close range.
        ///There were signs of struggle. He/She was also riddled with bullets at close range.
        ///There were signs of struggle. His/Her body was battered and had multiple bone fractures.
        ///His/Her body had bruises and minor fractures..
        /// </summary>
        internal static string MafiaD {
            get {
                return ResourceManager.GetString("MafiaD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current parity: .
        /// </summary>
        internal static string Parity {
            get {
                return ResourceManager.GetString("Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He/She had multiple stab wounds.
        ///There were signs of a struggle. He/She had bruises and some bone fractures.
        ///His/Her body was severely battered with many broken bones..
        /// </summary>
        internal static string SerialKillerD {
            get {
                return ResourceManager.GetString("SerialKillerD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were signs of struggle, but he/she apparently committed suicide.
        ///There were signs of struggle, but he/she apparently killed himself/herself.
        ///There were signs of struggle, but he/she apparently shot himself/herself..
        /// </summary>
        internal static string SuicideD {
            get {
                return ResourceManager.GetString("SuicideD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He/she was incinerated.
        ///He/She was burnt to death.
        ///He/She was killed in a fire..
        /// </summary>
        internal static string TerroristD {
            get {
                return ResourceManager.GetString("TerroristD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He/She was shot by a gunshot.
        ///He/She was ripped apart with several rounds from a gunshot.
        ///His/Her body had bruises and minor fractures.
        ///His/Her body was severely battered with many broken bones..
        /// </summary>
        internal static string VigilanteD {
            get {
                return ResourceManager.GetString("VigilanteD", resourceCulture);
            }
        }
    }
}
