//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApplication.Resources.GameStoryText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NightResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NightResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFApplication.Resources.GameStoryText.NightResources", typeof(NightResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You knew that this person would get on the right path. He is eager to server you cult..
        /// </summary>
        internal static string ECultusLeaderAct {
            get {
                return ResourceManager.GetString("ECultusLeaderAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your target had a strong will and failed to be convinced..
        /// </summary>
        internal static string ECultusLeaderActF {
            get {
                return ResourceManager.GetString("ECultusLeaderActF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that this person is dangerous..
        /// </summary>
        internal static string EDetectActDANGEROUS {
            get {
                return ResourceManager.GetString("EDetectActDANGEROUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that this person is peaceful..
        /// </summary>
        internal static string EDetectActPEACEFUL {
            get {
                return ResourceManager.GetString("EDetectActPEACEFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recruit has passed the loality test and is ready to serve you..
        /// </summary>
        internal static string EGodfatherAct {
            get {
                return ResourceManager.GetString("EGodfatherAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The potentional recruit turnet out to be useless to your clan, and may even pose a danger..
        /// </summary>
        internal static string EGodfatherActF {
            get {
                return ResourceManager.GetString("EGodfatherActF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems, that this person is {0}.
        /// </summary>
        internal static string EInvestigateAct {
            get {
                return ResourceManager.GetString("EInvestigateAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You went after your victim but he was not at home..
        /// </summary>
        internal static string EKillImmune {
            get {
                return ResourceManager.GetString("EKillImmune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today you tried to take control of someone&apos;s else mind. Who know what happened….
        /// </summary>
        internal static string EWitchAct {
            get {
                return ResourceManager.GetString("EWitchAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something thundered on the street. There was an accidend..
        /// </summary>
        internal static string KillActDRIVER_ACCIDENT {
            get {
                return ResourceManager.GetString("KillActDRIVER_ACCIDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cries for help were heard from the house, furniture was smashed, someone was struggling..
        /// </summary>
        internal static string KillActSUICIDE {
            get {
                return ResourceManager.GetString("KillActSUICIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone has just broken the door near your house. Shots were heard from there..
        /// </summary>
        internal static string MafiaActKILL {
            get {
                return ResourceManager.GetString("MafiaActKILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The night is going to end….
        /// </summary>
        internal static string NightEnd {
            get {
                return ResourceManager.GetString("NightEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems, the sun is gradually going down… The town is going to sleep..
        /// </summary>
        internal static string NightStart {
            get {
                return ResourceManager.GetString("NightStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} bullets..
        /// </summary>
        internal static string RemainingBullets {
            get {
                return ResourceManager.GetString("RemainingBullets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black clouds hung over the scene of the murder….
        /// </summary>
        internal static string RessurectAct {
            get {
                return ResourceManager.GetString("RessurectAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMINDER: You role is  .
        /// </summary>
        internal static string RoleRemind {
            get {
                return ResourceManager.GetString("RoleRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In one house, heart-rending screams and cries for help were heard..
        /// </summary>
        internal static string SerialKillerActKILL {
            get {
                return ResourceManager.GetString("SerialKillerActKILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night has began, nobody knows what will happened soon….
        /// </summary>
        internal static string StartAction {
            get {
                return ResourceManager.GetString("StartAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been recruited into the cult. You have abandoned all your ideals..
        /// </summary>
        internal static string TCultusLeaderAct {
            get {
                return ResourceManager.GetString("TCultusLeaderAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonight you decided to go to another part of the city by taxi..
        /// </summary>
        internal static string TDriverAct {
            get {
                return ResourceManager.GetString("TDriverAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosions were heard throughout the city, waking up all residents..
        /// </summary>
        internal static string TerroristAct {
            get {
                return ResourceManager.GetString("TerroristAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A beautiful stranger wandered to you, you could not resist her postponed all your deals..
        /// </summary>
        internal static string TEscortAct {
            get {
                return ResourceManager.GetString("TEscortAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lady friend came to you and complained about her live for a very long time..
        /// </summary>
        internal static string TEscortActOTHER {
            get {
                return ResourceManager.GetString("TEscortActOTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You spent this night alone with yourself contrary to whatever plans you had..
        /// </summary>
        internal static string TEscortActSELF {
            get {
                return ResourceManager.GetString("TEscortActSELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were recruited into the mafia clan offering untold fame and wealth in return for a small favor..
        /// </summary>
        internal static string TGodfatherAct {
            get {
                return ResourceManager.GetString("TGodfatherAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You woke up and it seems that the past was merely a dream, however soon you find stitches on your body..
        /// </summary>
        internal static string THealAct {
            get {
                return ResourceManager.GetString("THealAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some noises in your house….
        /// </summary>
        internal static string TKillAct {
            get {
                return ResourceManager.GetString("TKillAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You realized that you would never do that but your body dod not obey you. You fought the desire to commit suicide but it was all in vain….
        /// </summary>
        internal static string TKillActSUICIDE {
            get {
                return ResourceManager.GetString("TKillActSUICIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despite your injures you do not feel that your vitality is leaving you. You do not feel anything at all..
        /// </summary>
        internal static string TRessurectAct {
            get {
                return ResourceManager.GetString("TRessurectAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were overtaken by an acute to commit some act against your will as if your mind was controlled by someone..
        /// </summary>
        internal static string TWitchAct {
            get {
                return ResourceManager.GetString("TWitchAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rifle shot sounded somewhere nearby..
        /// </summary>
        internal static string VigilanteActKILL {
            get {
                return ResourceManager.GetString("VigilanteActKILL", resourceCulture);
            }
        }
    }
}
